server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.client: DEBUG
    org.springframework.messaging.simp: DEBUG
    org.springframework.messaging.simp.stomp: DEBUG
spring:
  application:
    name: spring-websocket-stomp
app:
  session:
    max-inactive-interval: 30s
  websocket:
    topic: /
    heartbeat:
      incoming-ms: 30000
      outgoing-ms: 0
    max-message-size-bytes: 52_428_800
    max-buffer-size-bytes: 1_073_741_824
    max-send-time-limit-ms: 30000
